### PR TITLE
Add Alice Colours

### PR DESCRIPTION
**Pull request by LazzaAU**
Will this be of benefit to Alice down the track ? EG: used for changing light colours

Idea being synonym is what will be triggered from user speech (slotRawValue) and if needed skill maker can use the slotValue to send a RGB code ? 

if not something you want let me know and i'll add it to the skill directly : )

PS: feel free to change colours to colors if that's preferred

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Yep, sure is!

Can you add the slot to FR, DE and IT please? Just a copy paste of the english one, because if they are missing, deployment will fail

**Comment by Psychokiller1888** [comment]
Now, please, don't hit me..... And don't take it bad either... We've based  Alice on EN-us.... I think `colours` is british english, and `colors`is US...

**Comment by LazzaAU** [comment]
hehe no worries, updated to suit :)

FYI... dont know why as i cant read other languages but the language files are all different sizes ? guessing its correct but hate to think the italians are missing out on stuff for example :)

eg : english = 29353 lines long
italian = 187567 lines

**Comment by Psychokiller1888** [comment]
Maybe less utterances, slots etc etc

**Pull request merged**
